fix: remove GA from cookie policy
gnosis/safe-landing-page pull request #19
Opened 2022-03-03 11:03 UTC by iamacook

## Overview
As part of our [analytics improvement](https://github.com/gnosis/safe-react/issues/3408), we no longer use GA and we therefore need not list details of their cookies.

2022-03-03 11:05 UTC, iamacook commented on src/pages/cookie.tsx
> -              Used to throttle request rate. Also used by Fortmatic wallet.
Fortmatic wallet is disabled on all chains. Their tracking won't occur.

2022-03-03 11:06 UTC, iamacook commented
Please hold off on merging this.

2022-03-03 11:16 UTC, iamacook commented on src/pages/cookie.tsx
> -              Used to throttle request rate. Also used by Fortmatic wallet.
I've just double-checked: `detectedWallet` doesn't detect Fortmatic either.

2022-03-07 09:42 UTC, DiogoSoaress requested changes
Isn't the `_gac_<property-id>` cookie also part of GA?

2022-03-07 10:52 UTC, DiogoSoaress approved these changes
🧹  nice!

2022-03-07 12:58 UTC, francovenica commented
Nothing to QA here. Just lets be sure this is not changed in prod until we have the new analytics implementation.

2022-03-08 13:13 UTC, germartinez requested changes
Be careful with this. The landing page itself is also using Google Analytics. That should be replaced before merging this PR.

2022-03-08 13:25 UTC, iamacook commented
> Be careful with this. The landing page itself is also using Google Analytics. That should be replaced before merging this PR.

Maybe this an unnecessary change for the time being then. @johannesmoormann, do we intend to implement GTM on the landing page?

2022-03-09 10:00 UTC, johannesmoormann commented
For now, the scope of the change is only for the web app, so let's leave GA in cookie policy.

2022-03-09 10:01 UTC, closed without merging